version: "3.2"

services:
  backend:
    image: shakakai/local-django-server:latest
    depends_on:
      - database
      - cache
      - mail
      - frontend
    volumes:
      - type: bind
          source: "${PROJECT_DIR}${BACKEND_DIR}"
          target: /app
    ports:
      - "${WEB_PORT}:5000"

  worker:
    image: shakakai/local-django-worker:latest
    depends_on:
      - database
      - cache
      - mail
    volumes:
      - type: bind
        source: "${PROJECT_DIR}${BACKEND_DIR}"
        target: /app
    ports: []
    command: /start-worker

  frontend:
    image: shakakai/local-frontend-server:latest
      volumes:
        - type: bind
            source: "${PROJECT_DIR}${FRONTEND_DIR}"
            target: /app
      environment:
        - NODE_VERSION
        - FRONTEND_BUILD_CMD
        - FRONTEND_DEV_CMD
        - FRONTEND_BUILD_DIR
      ports:
        - "${WEB_PORT}:8000"

  database:
    image: postgres:$POSTGRES_VERSION
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME
      - POSTGRES_PASSWORD
    ports:
      - "${POSTGRES_PORT}:5432"

  mail:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "${MAILHOG_HTTP_PORT}:8025"
      - "${MAILHOG_SMTP_PORT}:1025"

  cache:
    image: redis:5.0
    ports:
      - "${REDIS_PORT}:6379"
