version: "3.2"

services:

  backend:
    image: shakakai/local-django-server:latest
    depends_on:
      - database
      - cache
      - mail
      - frontend
    volumes:
      - type: bind
        source: $BACKEND_DIR
        target: /app
    ports:
      - "${BACKEND_PORT}:5000"

  worker:
    image: shakakai/local-django-worker:latest
    depends_on:
      - database
      - cache
      - mail
    volumes:
      - type: bind
        source: $BACKEND_DIR
        target: /app

  frontend_server:
    image: nginx:1.19.3
    volumes:
      - type: bind
        source: $FRONTEND_BUILD_DIR
        target: /usr/share/nginx/html
    ports:
      - "${FRONTEND_PORT}:80"

  frontend_builder:
    image: shakakai/local-frontend-builder:latest
    volumes:
      - type: bind
        source: $FRONTEND_DIR
        target: /app
    environment:
      - NODE_VERSION=$NODE_VERSION
      - FRONTEND_BUILD_CMD=$FRONTEND_BUILD_CMD
      - FRONTEND_DEV_CMD=$FRONTEND_DEV_CMD
      - FRONTEND_BUILD_DIR=$FRONTEND_BUILD_DIR
    ports:
      - "${FRONTEND_PORT}:80"

  database:
    image: postgres:$DATABASE_VERSION
    environment:
      - POSTGRES_USERNAME=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_PORT=$DATABASE_PORT
    ports:
      - "${DATABASE_PORT}:5432"

  mail:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "${EMAIL_HTTP_PORT}:8025"
      - "${EMAIL_SMTP_PORT}:1025"

  cache:
    image: redis:5.0
    ports:
      - "${CACHE_PORT}:6379"
